import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import StoreProvider from "@/store/providers";
import AuthGuard from "./components/AuthGuard";
import "./globals.css";
import "./index.css";
import Sidebar from "./components/layout/menu/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="main">
          <div className="side-bar">
            <Sidebar />
          </div>
          <div className="main-content">
            <div className="header bg-blue-950 text-white">
              School Of Hospitality
            </div>
            <div className="content">
              <StoreProvider>
                <AuthGuard>{children}</AuthGuard>
              </StoreProvider>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
